# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MCU51UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(704, 538)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.softwareTimer = QtWidgets.QWidget()
        self.softwareTimer.setObjectName("softwareTimer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.softwareTimer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.STsysClockFqy = QtWidgets.QLabel(self.softwareTimer)
        self.STsysClockFqy.setObjectName("STsysClockFqy")
        self.horizontalLayout_2.addWidget(self.STsysClockFqy)
        self.STsysClockFqyInput = QtWidgets.QLineEdit(self.softwareTimer)
        self.STsysClockFqyInput.setObjectName("STsysClockFqyInput")
        self.horizontalLayout_2.addWidget(self.STsysClockFqyInput)
        self.STsysClockUnit = QtWidgets.QLabel(self.softwareTimer)
        self.STsysClockUnit.setObjectName("STsysClockUnit")
        self.horizontalLayout_2.addWidget(self.STsysClockUnit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.STtimeLength = QtWidgets.QLabel(self.softwareTimer)
        self.STtimeLength.setObjectName("STtimeLength")
        self.horizontalLayout_2.addWidget(self.STtimeLength)
        self.STtimeLengthInput = QtWidgets.QLineEdit(self.softwareTimer)
        self.STtimeLengthInput.setObjectName("STtimeLengthInput")
        self.horizontalLayout_2.addWidget(self.STtimeLengthInput)
        self.STtimeLengthUnit = QtWidgets.QLabel(self.softwareTimer)
        self.STtimeLengthUnit.setObjectName("STtimeLengthUnit")
        self.horizontalLayout_2.addWidget(self.STtimeLengthUnit)
        self.STgenerate_btn = QtWidgets.QPushButton(self.softwareTimer)
        self.STgenerate_btn.setObjectName("STgenerate_btn")
        self.horizontalLayout_2.addWidget(self.STgenerate_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.STdisplay = QtWidgets.QTextBrowser(self.softwareTimer)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.STdisplay.setFont(font)
        self.STdisplay.setObjectName("STdisplay")
        self.verticalLayout.addWidget(self.STdisplay)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.softwareTimer, "")
        self.timerTimer = QtWidgets.QWidget()
        self.timerTimer.setObjectName("timerTimer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.timerTimer)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.timerTimer, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 704, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.STsysClockFqy.setText(_translate("MainWindow", "系统时钟频率"))
        self.STsysClockUnit.setText(_translate("MainWindow", "MHz"))
        self.STtimeLength.setText(_translate("MainWindow", "定时时间"))
        self.STtimeLengthUnit.setText(_translate("MainWindow", "微秒/μs"))
        self.STgenerate_btn.setText(_translate("MainWindow", "生成代码"))
        self.STdisplay.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Adobe Devanagari\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">void main(){</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">}</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.softwareTimer), _translate("MainWindow", "软件定时"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.timerTimer), _translate("MainWindow", "定时器定时"))
